# Generated by Django 3.0.5 on 2020-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('uuid', models.CharField(max_length=36)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('uuid', models.CharField(max_length=36)),
                ('start_month', models.IntegerField()),
                ('start_day', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('ticker_symbol', models.CharField(max_length=20)),
            ],
        ),
    ]
